Repository wuespace/deno-asn-generator, pull requests merged in 2024-12, with the labels that each got.

#5 Add OIDC Authentication support
  .github/workflows/deno-ci.yml
  Dockerfile
  README.md
  deno.json
  deno.lock
  example.env
  lib/http/asn-metadata-from-context.ts
  lib/http/middleware/oidc.ts
  lib/http/routes/api.ts
  lib/http/routes/svg.ts
  lib/http/routes/ui.tsx
Labels: :pushpin: security, :tulip: enhancement

#9 Add OIDC callback route to http app
  lib/http/mod.ts
Labels: :bug: bug

#10 Rewrite configuration / environment logic using `@wuespace/envar`
  DEPLOY.md
  README.md
  compose.yml
  deno.json
  deno.lock
  env.md
  example.env
  lib/cli/bump.ts
  lib/cli/server.ts
  lib/cli/stats.ts
  lib/common/additional-managed-namespaces.ts
  lib/common/asn.ts
  lib/common/config.ts
  lib/common/db.ts
  lib/common/namespaces.ts
  lib/common/path.ts
  lib/common/zod-helpers.ts
  lib/http/barcode-svg.ts
  lib/http/lookup-url.ts
  lib/http/routes/lookup.ts
  lib/http/routes/ui.tsx
  lib/http/ui/index.tsx
  lib/http/ui/search.tsx
  lib/http/ui/wrapper.tsx
  main.ts
Labels: :tulip: enhancement
